// Code generated by "stringer -type=HashAlg"; DO NOT EDIT.

package gopherbounce

import "strconv"

const _HashAlg_name = "BcryptAlgScryptAlgArgon2iAlgArgon2idAlg"

var _HashAlg_index = [...]uint8{0, 9, 18, 28, 39}

func (i HashAlg) String() string {
	if i < 0 || i >= HashAlg(len(_HashAlg_index)-1) {
		return "HashAlg(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HashAlg_name[_HashAlg_index[i]:_HashAlg_index[i+1]]
}
